CREATE TABLE PROFILES
(
	ID SMALLINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
	USERNAME VARCHAR(20) NOT NULL UNIQUE,
	PASSWORD VARCHAR(20) NOT NULL,
	NICKNAME VARCHAR(20),
	FIRSTNAME VARCHAR(20),
	LASTNAME VARCHAR(20),
	EMAIL VARCHAR(20),
	ADDRESS VARCHAR(20),
	DOB DATE,
	CREDIT INT,
	STATUS SMALLINT,
	ADMIN SMALLINT
);