CREATE TABLE PROFILES
(
	USERNAME VARCHAR(20) NOT NULL PRIMARY KEY,
	PASSWORD VARCHAR(20) NOT NULL,
	NICKNAME VARCHAR(20),
	FIRSTNAME VARCHAR(20),
	LASTNAME VARCHAR(20),
	EMAIL VARCHAR(20),
	ADDRESS VARCHAR(20),
	DOB DATE,
	CREDIT INT,
	STATUS SMALLINT,
	ADMIN SMALLINT
);

CREATE TABLE ITEMS
(
	ID SMALLINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
	TITLE VARCHAR(20) NOT NULL,
	CATEGORY VARCHAR(20) NOT NULL,
	PICTURE VARCHAR(20),
	DESCRIPTION VARCHAR(20) NOT NULL,
	POSTAGE VARCHAR(20),
	RESERVE DECIMAL(5),
	START DECIMAL(5),
	INC DECIMAL(5),
	OWNER VARCHAR(20) NOT NULL,
	STATUS SMALLINT,
	BIDDER VARCHAR(20),
	BID DECIMAL(5)
);