DROP TABLE USERS;
DROP TABLE ITEMS;

CREATE TABLE ITEMS
(
	ID SMALLINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	TITLE VARCHAR(24) NOT NULL,
	CATEGORY VARCHAR(24) NOT NULL,
	PICTURE VARCHAR(64),
	DESCRIPTION VARCHAR(140),
	POSTAGE VARCHAR(24),
	CATEGORY VARCHAR(24) NOT NULL,
	RESERVE NUMERIC,
	START_BID NUMERIC,
	INC_BID NUMERIC,
	END_TIME DATE,
	OWNER SMALLINT NOT NULL,
	BIDDER SMALLINT,
	BID NUMERIC,
	STATUS SMALLINT NOT NULL,
	CONSTRAINT ID_PK PRIMARY KEY (ID)
	FOREIGN KEY ("OWNER") REFERENCES USERS("ID")
	FOREIGN KEY ("BIDDER") REFERENCES USERS("ID")
);

CREATE TABLE USERS
(
	ID SMALLINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	USERNAME VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(20) NOT NULL,
	NICKNAME VARCHAR(20),
	FIRSTNAME VARCHAR(20),
	LASTNAME VARCHAR(20),
	EMAIL VARCHAR(20),
	ADDRESS VARCHAR(20),
	DOB DATE,
	CREDIT INT,
	STATUS SMALLINT,
	CONSTRAINT ID_PK PRIMARY KEY (ID)
	FOREIGN KEY ("OWNER") REFERENCES USERS("ID")
	FOREIGN KEY ("BIDDER") REFERENCES USERS("ID")
);

CREATE TABLE TBL_CHARACTERS (
	MVCHAR_ID INTEGER CONSTRAINT MVCHAR_PK PRIMARY KEY,
	MVCHAR_NAME VARCHAR(20),
	DIET VARCHAR(20),
	SOUNDS VARCHAR(20)
);

CREATE TABLE TBL_COMMENTS (
	COMMENT_ID SMALLINT NOT NULL GENERATED ALWAYS AS IDENTITY,
	PRIMARY KEY(COMMENT_ID),
	MVCHAR_ID INTEGER CONSTRAINT CHAR_FK REFERENCES TBL_CHARACTERS,
	MVCHAR_NAME VARCHAR(20),
	USERNAME VARCHAR(20) NOT NULL,
	COMMENT_DATE DATE,
	COMMENT LONG VARCHAR NOT NULL
);
