SELECT * FROM PROFILES;
SELECT USERNAME FROM PROFILES;
SELECT COUNT(*) FROM PROFILES WHERE USERNAME = 'stephen';
SELECT * FROM PROFILES WHERE USERNAME = 'stephen';


SELECT * FROM ITEMS;
SELECT * FROM ITEMS WHERE OWNER = 'stephen';
SELECT * FROM ITEMS WHERE STATUS = 1;
SELECT * FROM ITEMS WHERE TITLE LIKE '%box%'