CREATE TABLE STUDENTS (
	NAME VARCHAR(20)
);

INSERT INTO STUDENTS VALUES ('zombies');
INSERT INTO STUDENTS VALUES ('pirates');
INSERT INTO STUDENTS VALUES ('vampires');
INSERT INTO STUDENTS VALUES ('ninjas');